#ifndef CMEERROR_H
#define CMEERROR_H

#endif

typedef enum
{
    CMS_PHONE_FAILURE = 0,
    CMS_NO_CONNECTION_TO_PHONE,
    CMS_PHONE_ADAPTOR_LINK_RESERVED,
    CMS_OPERATION_NOT_ALLOWED,
    CMS_OPERATION_NOT_SUPPORTED,
    CMS_PH_SIM_PIN_REQUIRED,
    CMS_PH_FSIM_PIN_REQUIRED,
    CMS_PH_FSIM_PUK_REQUIRED,
    CMS_SIM_NOT_INSERTED = 10,
    CMS_SIM_PIN_REQUIRED,
    CMS_SIM_PUK_REQUIRED,
    CMS_SIM_FAILURE,
    CMS_SIM_BUSY,
    CMS_SIM_WRONG,
    CMS_INCORRECT_PASSWORD,
    CMS_SIM_PIN2_REQUIRED,
    CMS_SIM_PUK2_REQUIRED,
    CMS_MEMORY_FULL = 20,
    CMS_INVALID_INDEX,
    CMS_NOT_FOUND,
    CMS_MEMORY_FAILURE,
    CMS_TEXT_STRING_TOO_LONG,
    CMS_INVALID_CHARACTERS_IN_TEXT_STRING,
    CMS_DIAL_STRING_TOO_LONG = 26,
    CMS_INVALID_CHARACTERS_IN_DIAL_STRING,
    CMS_NO_NETWORK_SERVICE = 30,
    CMS_NETWORK_TIMEOUT,
    CMS_NETWORK_NOT_ALLOWED_EMERGENCY_ONLY,
    CMS_NETWORK_PERSONALIZATION_PIN_REQUIRED = 40,
    CMS_NETWORK_PERSONALIZATION_PUK_REQUIRED,
    CMS_NETWORK_SUBSET_PERSONALIZATION_PIN_REQUIRED,
    CMS_NETWORK_SUBSET_PERSONALIZATION_PUK_REQUIRED,
    CMS_SERVICE_PROVIDER_PERSONALIZATION_PIN_REQUIRED,
    CMS_SERVICE_PROVIDER_PERSONALIZATION_PUK_REQUIRED,
    CMS_CORPORATE_PERSONALIZATION_PIN_REQUIRED,
    CMS_CORPORATE_PERSONALIZATION_PUK_REQUIRED,
    CMS_AUDIO_UNKNOWN_ERROR = 901,
    CMS_AUDIO_INVALID_PARAMETERS,
    CMS_AUDIO_OPERATION_NOT_SUPPORTED,
    CMS_AUDIO_DEVICE_BUSY
} Cme_Error_t;


typedef struct
{
	Cme_Error_t status;
	const char* response;
	
}Cme_Error_Response_t;

extern const Cme_Error_Response_t CME_ERROR_RESPONSE[];
